vti_encoding:SR|utf8-nl
vti_author:SR|LATITUDE-E5430\\gregaryb
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timelastmodified:TR|27 Jul 2026 05:45:04 -0000
vti_timecreated:TR|15 Mar 2026 02:16:50 -0000
vti_title:SR|Site History
vti_extenderversion:SR|12.0.0.0
vti_backlinkinfo:VX|admin/approve_sponsorship.php milestones/milestones.php Information/annual_reports/annual_reports.php Information/strategic_plan/strategic_plan.html personnel_history/personnel_history.html admin/expression_web_4_beginners.php admin/javascript_4_beginners.php governance/forms/forms.php Information/association_rules/association_rules.html ACNC/plan/plan.html ACNC/reports/reports.php contribute/join.php governance/governance.php governance/policies/policies.php governance/reports/reports.php request_sponsorship.php site_history/site_history.php Information/cool_space/cool_space.html CoolSpace/information.html admin/web_diagnostics.php contribute/contribute.php governance/plan/plan.php index.php sponsorship_request_sent.php ACNC/ACNC.html ACNC/policies_rules/policies_rules.php master.dwt admin/css_4_beginners.php admin/edit_groups.php admin/friday_feast_menu.php contact/contact.php contribute/volunteering.php people/people.php events/cyber_cafe/cybercafe.php Information/Policies/policies.html admin/administration.php admin/governance.php admin/renew_sponsorship.php Calendar/calendar.php contribute/donation.php contribute/why_donate.php Information/information.html about/about.php room/room.php admin/html_4_beginners.php governance/rules/rules.php groups/groups\\ .php sponsors/sponsors.php
vti_nexttolasttimemodified:TR|27 Jul 2026 05:44:07 -0000
vti_cacheddtm:TX|27 Jul 2026 05:45:04 -0000
vti_filesize:IR|19433
vti_cachedtitle:SR|Site History
vti_cachedbodystyle:SR|<body onload="DoOnPageLoadComplete()">
vti_cachedlinkinfo:VX|G|../master.dwt H|https://www.millhouse.org.au/ Q|../styles/style4PC.css H|../favicon.jpg S|../common.js H|https://fonts.googleapis.com H|https://fonts.gstatic.com Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 H|../images/MillHouse.jpg S|../images/MillHouse.jpg H|../images/MillHouseNeighborhoodHouse1.jpg S|../images/MillHouseNeighborhoodHouse1.jpg H|../images/MillHouseNeighborhoodHouse2.jpg S|../images/MillHouseNeighborhoodHouse2.jpg S|../sponsors/images/NHHV.png S|../sponsors/images/VicStateGov.jpg S|../sponsors/images/CentralGoldfields.png S|../sponsors/images/FRRR.png S|../sponsors/images/BendigoBank.jpg S|../sponsors/images/JWR.png S|../sponsors/images/WattleOffice.jpg S|../sponsors/images/FoodBank.png S|../sponsors/images/FoodShare.png S|../sponsors/images/Aldi.png S|../sponsors/images/ParkviewBakery.jpg S|../sponsors/images/MaryboroughFloorCoverings.jpg S|../sponsors/images/SilverService.png S|../sponsors/images/GoldfieldsScreens.png H|../index.php H|../about/about.php H|../Calendar/Calendar.php H|../room/room.php H|../sponsors/sponsors.php H|../contribute/contribute.php H|../contribute/join.php H|../contribute/volunteering.php H|../request_sponsorship.php H|../contribute/donation.php H|../contact/Contact.php H|site_history.php H|../governance/governance.php H|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile H|../governance/rules/rules.php H|../governance/reports/reports.php H|../governance/policies/policies.php H|../governance/plan/plan.php H|../admin/administration.php H|../admin/edit_groups.php H|../admin/approve_sponsorship.php H|../admin/renew_sponsorship.php H|../admin/friday_feast_menu.php H|../admin/governance.php H|../governance/forms/forms.php H|../admin/web_diagnostics.php H|../admin/html_4_beginners.php H|../admin/css_4_beginners.php H|../admin/javascript_4_beginners.php H|../admin/expression_web_4_beginners.php H|images/OldKnittingMillAerial.jpg S|images/OldKnittingMillAerial.jpg H|images/DyeHousePlaque.jpg S|images/DyeHousePlaque.jpg H|images/Church.jpg S|images/Church.jpg H|images/ChurchPlaque.jpg S|images/ChurchPlaque.jpg S|images/ChimneyConstruction.jpg S|images/KnittingMill.jpg S|images/Workers1.jpg S|images/Workers2.jpg S|images/Workers3.jpg S|images/Workers4.jpg
vti_cachedsvcrellinks:VX|FGUS|master.dwt NHSS|https://www.millhouse.org.au/ FQUS|styles/style4PC.css NHUS|favicon.jpg FSUS|common.js NHSS|https://fonts.googleapis.com NHSS|https://fonts.gstatic.com NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 FHUS|images/MillHouse.jpg FSUS|images/MillHouse.jpg FHUS|images/MillHouseNeighborhoodHouse1.jpg FSUS|images/MillHouseNeighborhoodHouse1.jpg FHUS|images/MillHouseNeighborhoodHouse2.jpg FSUS|images/MillHouseNeighborhoodHouse2.jpg FSUS|sponsors/images/NHHV.png FSUS|sponsors/images/VicStateGov.jpg FSUS|sponsors/images/CentralGoldfields.png FSUS|sponsors/images/FRRR.png FSUS|sponsors/images/BendigoBank.jpg FSUS|sponsors/images/JWR.png FSUS|sponsors/images/WattleOffice.jpg FSUS|sponsors/images/FoodBank.png FSUS|sponsors/images/FoodShare.png FSUS|sponsors/images/Aldi.png FSUS|sponsors/images/ParkviewBakery.jpg FSUS|sponsors/images/MaryboroughFloorCoverings.jpg FSUS|sponsors/images/SilverService.png FSUS|sponsors/images/GoldfieldsScreens.png FHUS|index.php FHUS|about/about.php FHUS|Calendar/Calendar.php FHUS|room/room.php FHUS|sponsors/sponsors.php FHUS|contribute/contribute.php FHUS|contribute/join.php FHUS|contribute/volunteering.php FHUS|request_sponsorship.php FHUS|contribute/donation.php FHUS|contact/Contact.php FHUS|site_history/site_history.php FHUS|governance/governance.php NHSS|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile FHUS|governance/rules/rules.php FHUS|governance/reports/reports.php FHUS|governance/policies/policies.php FHUS|governance/plan/plan.php FHUS|admin/administration.php FHUS|admin/edit_groups.php FHUS|admin/approve_sponsorship.php FHUS|admin/renew_sponsorship.php FHUS|admin/friday_feast_menu.php FHUS|admin/governance.php FHUS|governance/forms/forms.php FHUS|admin/web_diagnostics.php FHUS|admin/html_4_beginners.php FHUS|admin/css_4_beginners.php FHUS|admin/javascript_4_beginners.php FHUS|admin/expression_web_4_beginners.php FHUS|site_history/images/OldKnittingMillAerial.jpg FSUS|site_history/images/OldKnittingMillAerial.jpg FHUS|site_history/images/DyeHousePlaque.jpg FSUS|site_history/images/DyeHousePlaque.jpg FHUS|site_history/images/Church.jpg FSUS|site_history/images/Church.jpg FHUS|site_history/images/ChurchPlaque.jpg FSUS|site_history/images/ChurchPlaque.jpg FSUS|site_history/images/ChimneyConstruction.jpg FSUS|site_history/images/KnittingMill.jpg FSUS|site_history/images/Workers1.jpg FSUS|site_history/images/Workers2.jpg FSUS|site_history/images/Workers3.jpg FSUS|site_history/images/Workers4.jpg
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8 viewport width=device-width,\\ initial-scale=1.0 description Mill\\ House\\ -\\ Neighborhood\\ House.\\ Providing\\ assistance\\ and\\ social\\ engagement\\ to\\ residents\\ of\\ Maryborough\\ and\\ the\\ central\\ goldfields\\ region. keywords Maryborough,\\ central\\ goldfields,\\ NIL,\\ no\\ interest\\ loans,\\ employment\\ services,\\ clubs,\\ hobbies,\\ Friday\\ feast,\\ Thursday\\ cafe,\\ volunteering,\\ membership,\\ market\\ days,\\ free\\ food. author Sarah\\ McLean
vti_charset:SR|utf-8
