vti_encoding:SR|utf8-nl
vti_author:SR|LATITUDE-E5430\\gregaryb
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timelastmodified:TR|25 Sep 2026 04:07:00 -0000
vti_timecreated:TR|17 Sep 2026 11:09:25 -0000
vti_extenderversion:SR|12.0.0.0
vti_backlinkinfo:VX|what/groups/groups_content.php
vti_nexttolasttimemodified:TR|25 Sep 2026 04:06:21 -0000
vti_cacheddtm:TX|25 Sep 2026 04:07:00 -0000
vti_filesize:IR|7283
vti_cachedlinkinfo:VX|K|groups_content.php K|groups_content.php K|groups_content.php K|groups_content.php K|groups_content.php K|groups_content.php K|groups_content.php K|groups_content.php H|top H|../../images/maker_mums.jpg S|../../images/maker_mums.jpg H|images/maker_mums.jpg S|images/maker_mums.jpg H|top H|https://www.dungeonsanddragons.com/ H|https://en.wikipedia.org/wiki/Dungeons_&_Dragons H|images/dungeons_dragons.jpg S|images/dungeons_dragons.jpg H|../groups/images/dungeons_dragons2.jpg S|../groups/images/dungeons_dragons2.jpg H|top H|../../images/scrappers.jpg S|../../images/scrappers.jpg H|images/scrappers.jpg S|images/scrappers.jpg H|images/scrappers2.jpg S|images/scrappers2.jpg H|images/scrappers3.jpg S|images/scrappers3.jpg H|images/scrappers4.jpg S|images/scrappers4.jpg H|images/scrappers5.jpg S|images/scrappers5.jpg H|top H|images/yarn.jpg S|images/yarn.jpg H|top H|images/art4soul.jpg S|images/art4soul.jpg H|top H|../../images/canasta.jpg S|../../images/canasta.jpg H|images/canasta.jpg S|images/canasta.jpg H|top H|../../images/u3a_books.jpg S|../../images/u3a_books.jpg H|images/u3a_writers.jpg S|images/u3a_writers.jpg H|images/u3a_digital_photobooks.jpg S|images/u3a_digital_photobooks.jpg H|top
vti_cachedsvcrellinks:VX|FKUS|what/groups/groups_content.php FKUS|what/groups/groups_content.php FKUS|what/groups/groups_content.php FKUS|what/groups/groups_content.php FKUS|what/groups/groups_content.php FKUS|what/groups/groups_content.php FKUS|what/groups/groups_content.php FKUS|what/groups/groups_content.php NHUS|what/groups/top FHUS|images/maker_mums.jpg FSUS|images/maker_mums.jpg FHUS|what/groups/images/maker_mums.jpg FSUS|what/groups/images/maker_mums.jpg NHUS|what/groups/top NHSS|https://www.dungeonsanddragons.com/ NHSS|https://en.wikipedia.org/wiki/Dungeons_&_Dragons FHUS|what/groups/images/dungeons_dragons.jpg FSUS|what/groups/images/dungeons_dragons.jpg FHUS|what/groups/images/dungeons_dragons2.jpg FSUS|what/groups/images/dungeons_dragons2.jpg NHUS|what/groups/top FHUS|images/scrappers.jpg FSUS|images/scrappers.jpg FHUS|what/groups/images/scrappers.jpg FSUS|what/groups/images/scrappers.jpg FHUS|what/groups/images/scrappers2.jpg FSUS|what/groups/images/scrappers2.jpg FHUS|what/groups/images/scrappers3.jpg FSUS|what/groups/images/scrappers3.jpg FHUS|what/groups/images/scrappers4.jpg FSUS|what/groups/images/scrappers4.jpg FHUS|what/groups/images/scrappers5.jpg FSUS|what/groups/images/scrappers5.jpg NHUS|what/groups/top FHUS|what/groups/images/yarn.jpg FSUS|what/groups/images/yarn.jpg NHUS|what/groups/top FHUS|what/groups/images/art4soul.jpg FSUS|what/groups/images/art4soul.jpg NHUS|what/groups/top FHUS|images/canasta.jpg FSUS|images/canasta.jpg FHUS|what/groups/images/canasta.jpg FSUS|what/groups/images/canasta.jpg NHUS|what/groups/top FHUS|images/u3a_books.jpg FSUS|images/u3a_books.jpg FHUS|what/groups/images/u3a_writers.jpg FSUS|what/groups/images/u3a_writers.jpg FHUS|what/groups/images/u3a_digital_photobooks.jpg FSUS|what/groups/images/u3a_digital_photobooks.jpg NHUS|what/groups/top
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|utf-8
