vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|28 Aug 2026 11:47:23 -0000
vti_extenderversion:SR|12.0.0.0
vti_author:SR|LATITUDE-E5430\\gregaryb
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timecreated:TR|15 Aug 2026 15:37:15 -0000
vti_title:SR|CSS for Beginners
vti_backlinkinfo:VX|administration/PageEditInstructions.html
vti_nexttolasttimemodified:TR|28 Aug 2026 11:28:07 -0000
vti_cacheddtm:TX|28 Aug 2026 11:47:23 -0000
vti_filesize:IR|62587
vti_cachedtitle:SR|CSS for Beginners
vti_cachedbodystyle:SR|<body onload="DoOnPageLoadComplete()">
vti_cachedlinkinfo:VX|G|../master.dwt H|https://www.millhouse.org.au/ Q|../styles/style4PC.css H|../favicon.jpg S|../common.js H|https://fonts.googleapis.com H|https://fonts.gstatic.com Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 S|/voices/MainMenu.mp3 H|../images/MillHouse.jpg S|../images/MillHouse.jpg H|../images/MillHouseNeighborhoodHouse1.jpg S|../images/MillHouseNeighborhoodHouse1.jpg H|../images/MillHouseNeighborhoodHouse2.jpg S|../images/MillHouseNeighborhoodHouse2.jpg H|../index.php H|../about/about.php H|../calendar/calendar.php H|../room/room.php H|../sponsors/sponsors.php H|../contribute/contribute.php H|../contribute/join.php H|../contribute/volunteering.php H|../contribute/request_sponsorship.php H|../contribute/donation.php H|../contact/contact.php H|../site_history/site_history.php H|../governance/governance.php H|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile H|../governance/rules/rules.php H|../governance/reports/reports.php H|../governance/policies/policies.php H|../governance/plan/plan.php H|../group_events/group_events.php H|administration.php H|https://www.w3schools.com/cssref/index.php S|images/StyleProperty.jpg S|images/StyleTags.jpg K|../\\\\html_4_beginners.html H|https://www.w3schools.com/tags/tag_link.asp S|images/StyleCSS.jpg H|https://www.w3schools.com/tags/ref_colornames.asp H|https://www.w3schools.com/html/html_colors_hex.asp H|https://www.w3schools.com/colors/colors_rgb.asp H|https://www.w3schools.com/colors/colors_hsl.asp H|https://www.w3schools.com/css/css_border.asp H|https://www.w3schools.com/cssref/pr_class_display.php H|https://www.w3schools.com/cssref/pr_font_font-family.php H|https://fonts.google.com/ H|https://www.w3schools.com/cssref/pr_font_weight.php H|https://www.w3schools.com/cssref/pr_font_font-style.php H|https://www.w3schools.com/cssref/pr_font_font-size.php H|https://www.w3schools.com/css/css_text.asp H|https://www.w3schools.com/cssref/pr_class_position.php H|https://www.w3schools.com/cssref/playit.php H|https://www.w3schools.com/cssref/playit.php H|https://www.w3schools.com/cssref/playit.php H|https://www.w3schools.com/cssref/tryit.php H|https://www.w3schools.com/cssref/pr_pos_vertical-align.php H|https://www.w3schools.com/cssref/pr_margin.php H|https://www.w3schools.com/cssref/pr_padding.php H|https://www.w3schools.com/cssref/css_ref_pseudo_classes.php H|https://www.w3schools.com/css/default.asp
vti_cachedsvcrellinks:VX|FGUS|master.dwt NHSS|https://www.millhouse.org.au/ FQUS|styles/style4PC.css FHUS|favicon.jpg FSUS|common.js NHSS|https://fonts.googleapis.com NHSS|https://fonts.gstatic.com NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 NSUS|/voices/MainMenu.mp3 FHUS|images/MillHouse.jpg FSUS|images/MillHouse.jpg FHUS|images/MillHouseNeighborhoodHouse1.jpg FSUS|images/MillHouseNeighborhoodHouse1.jpg FHUS|images/MillHouseNeighborhoodHouse2.jpg FSUS|images/MillHouseNeighborhoodHouse2.jpg FHUS|index.php FHUS|about/about.php FHUS|calendar/calendar.php FHUS|room/room.php FHUS|sponsors/sponsors.php FHUS|contribute/contribute.php FHUS|contribute/join.php FHUS|contribute/volunteering.php FHUS|contribute/request_sponsorship.php FHUS|contribute/donation.php FHUS|contact/contact.php FHUS|site_history/site_history.php FHUS|governance/governance.php NHSS|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile FHUS|governance/rules/rules.php FHUS|governance/reports/reports.php FHUS|governance/policies/policies.php FHUS|governance/plan/plan.php FHUS|group_events/group_events.php FHUS|administration/administration.php NHSS|https://www.w3schools.com/cssref/index.php FSUS|administration/images/StyleProperty.jpg FSUS|administration/images/StyleTags.jpg NHUS|file:///C:/Users/gregaryb/Documents/GitHub/Millhouse-Website/\\\\html_4_beginners.html NHSS|https://www.w3schools.com/tags/tag_link.asp FSUS|administration/images/StyleCSS.jpg NHSS|https://www.w3schools.com/tags/ref_colornames.asp NHSS|https://www.w3schools.com/html/html_colors_hex.asp NHSS|https://www.w3schools.com/colors/colors_rgb.asp NHSS|https://www.w3schools.com/colors/colors_hsl.asp NHSS|https://www.w3schools.com/css/css_border.asp NHSS|https://www.w3schools.com/cssref/pr_class_display.php NHSS|https://www.w3schools.com/cssref/pr_font_font-family.php NHSS|https://fonts.google.com/ NHSS|https://www.w3schools.com/cssref/pr_font_weight.php NHSS|https://www.w3schools.com/cssref/pr_font_font-style.php NHSS|https://www.w3schools.com/cssref/pr_font_font-size.php NHSS|https://www.w3schools.com/css/css_text.asp NHSS|https://www.w3schools.com/cssref/pr_class_position.php NHSS|https://www.w3schools.com/cssref/playit.php NHSS|https://www.w3schools.com/cssref/playit.php NHSS|https://www.w3schools.com/cssref/playit.php NHSS|https://www.w3schools.com/cssref/tryit.php NHSS|https://www.w3schools.com/cssref/pr_pos_vertical-align.php NHSS|https://www.w3schools.com/cssref/pr_margin.php NHSS|https://www.w3schools.com/cssref/pr_padding.php NHSS|https://www.w3schools.com/cssref/css_ref_pseudo_classes.php NHSS|https://www.w3schools.com/css/default.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8 viewport width=device-width,\\ initial-scale=1.0 description Mill\\ House\\ -\\ Neighborhood\\ House.\\ Providing\\ assistance\\ and\\ social\\ engagement\\ to\\ residents\\ of\\ Maryborough\\ and\\ the\\ central\\ goldfields\\ region. keywords Maryborough,\\ central\\ goldfields,\\ NIL,\\ no\\ interest\\ loans,\\ employment\\ services,\\ clubs,\\ hobbies,\\ Friday\\ feast,\\ Thursday\\ cafe,\\ volunteering,\\ membership,\\ market\\ days,\\ free\\ food. author Sarah\\ McLean
vti_charset:SR|utf-8
