vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|02 Sep 2026 04:49:47 -0000
vti_extenderversion:SR|12.0.0.0
vti_author:SR|LATITUDE-E5430\\gregaryb
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timecreated:TR|15 Aug 2026 15:38:07 -0000
vti_title:SR|HTML for Beginners
vti_backlinkinfo:VX|administration/PageEditInstructions.html
vti_nexttolasttimemodified:TR|02 Sep 2026 04:48:54 -0000
vti_cacheddtm:TX|02 Sep 2026 04:49:47 -0000
vti_filesize:IR|52744
vti_cachedtitle:SR|HTML for Beginners
vti_cachedbodystyle:SR|<body onload="DoOnPageLoadComplete()">
vti_cachedlinkinfo:VX|G|../master.dwt H|https://www.millhouse.org.au/ Q|../styles/style4PC.css H|../favicon.jpg S|../common.js H|https://fonts.googleapis.com H|https://fonts.gstatic.com Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 H|../images/MillHouse.jpg S|../images/MillHouse.jpg H|../images/MillHouseNeighborhoodHouse1.jpg S|../images/MillHouseNeighborhoodHouse1.jpg H|../images/MillHouseNeighborhoodHouse2.jpg S|../images/MillHouseNeighborhoodHouse2.jpg H|../index.php H|../about/about.php H|../calendar/calendar.php H|../room/room.php H|../sponsors/sponsors.php H|../contribute/contribute.php H|../contribute/join.php H|../contribute/volunteering.php H|../contribute/request_sponsorship.php H|../contribute/donation.php H|../contact/contact.php H|../site_history/site_history.php H|../governance/governance.php H|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile H|../governance/rules/rules.php H|../governance/reports/reports.php H|../governance/policies/policies.php H|../governance/plan/plan.php H|../group_events/group_events.php H|administration.php H|https://www.w3schools.com/TAGS/default.asp S|images/CubeOnCube.jpg S|images/CubeInCube.jpg S|images/CubeHalfInCube.jpg S|images/BrowserWindow.jpg S|images/BrowserWindowBoxWidth.jpg S|images/CubeInCubeWidth.jpg S|images/SpansInDiv.jpg S|images/NewHTML.jpg H|https://www.w3schools.com/tags/tag_doctype.ASP H|https://www.w3schools.com/tags/tag_html.asp H|https://www.w3schools.com/tags/tag_head.asp H|https://www.w3schools.com/tags/tag_title.asp H|https://www.w3schools.com/tags/tag_style.asp H|https://www.w3schools.com/tags/tag_link.asp H|https://www.w3schools.com/tags/tag_header.asp H|https://www.w3schools.com/tags/tag_body.asp H|https://www.w3schools.com/tags/tag_footer.asp S|https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Information_icon.svg/960px-Information_icon.svg.png S|https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Information_icon.svg/960px-Information_icon.svg.png S|https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Information_icon.svg/960px-Information_icon.svg.png H|https://google.com H|https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Information_icon.svg/960px-Information_icon.svg.png S|https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Information_icon.svg/960px-Information_icon.svg.png H|https://www.w3schools.com/charsets/ref_emoji_smileys.asp
vti_cachedsvcrellinks:VX|FGUS|master.dwt NHSS|https://www.millhouse.org.au/ FQUS|styles/style4PC.css FHUS|favicon.jpg FSUS|common.js NHSS|https://fonts.googleapis.com NHSS|https://fonts.gstatic.com NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 FHUS|images/MillHouse.jpg FSUS|images/MillHouse.jpg FHUS|images/MillHouseNeighborhoodHouse1.jpg FSUS|images/MillHouseNeighborhoodHouse1.jpg FHUS|images/MillHouseNeighborhoodHouse2.jpg FSUS|images/MillHouseNeighborhoodHouse2.jpg FHUS|index.php FHUS|about/about.php FHUS|calendar/calendar.php FHUS|room/room.php FHUS|sponsors/sponsors.php FHUS|contribute/contribute.php FHUS|contribute/join.php FHUS|contribute/volunteering.php FHUS|contribute/request_sponsorship.php FHUS|contribute/donation.php FHUS|contact/contact.php FHUS|site_history/site_history.php FHUS|governance/governance.php NHSS|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile FHUS|governance/rules/rules.php FHUS|governance/reports/reports.php FHUS|governance/policies/policies.php FHUS|governance/plan/plan.php FHUS|group_events/group_events.php FHUS|administration/administration.php NHSS|https://www.w3schools.com/TAGS/default.asp FSUS|administration/images/CubeOnCube.jpg FSUS|administration/images/CubeInCube.jpg FSUS|administration/images/CubeHalfInCube.jpg FSUS|administration/images/BrowserWindow.jpg FSUS|administration/images/BrowserWindowBoxWidth.jpg FSUS|administration/images/CubeInCubeWidth.jpg FSUS|administration/images/SpansInDiv.jpg FSUS|administration/images/NewHTML.jpg NHSS|https://www.w3schools.com/tags/tag_doctype.ASP NHSS|https://www.w3schools.com/tags/tag_html.asp NHSS|https://www.w3schools.com/tags/tag_head.asp NHSS|https://www.w3schools.com/tags/tag_title.asp NHSS|https://www.w3schools.com/tags/tag_style.asp NHSS|https://www.w3schools.com/tags/tag_link.asp NHSS|https://www.w3schools.com/tags/tag_header.asp NHSS|https://www.w3schools.com/tags/tag_body.asp NHSS|https://www.w3schools.com/tags/tag_footer.asp NSSS|https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Information_icon.svg/960px-Information_icon.svg.png NSSS|https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Information_icon.svg/960px-Information_icon.svg.png NSSS|https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Information_icon.svg/960px-Information_icon.svg.png NHSS|https://google.com NHSS|https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Information_icon.svg/960px-Information_icon.svg.png NSSS|https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Information_icon.svg/960px-Information_icon.svg.png NHSS|https://www.w3schools.com/charsets/ref_emoji_smileys.asp
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8 viewport width=device-width,\\ initial-scale=1.0 description Mill\\ House\\ -\\ Neighborhood\\ House.\\ Providing\\ assistance\\ and\\ social\\ engagement\\ to\\ residents\\ of\\ Maryborough\\ and\\ the\\ central\\ goldfields\\ region. keywords Maryborough,\\ central\\ goldfields,\\ NIL,\\ no\\ interest\\ loans,\\ employment\\ services,\\ clubs,\\ hobbies,\\ Friday\\ feast,\\ Thursday\\ cafe,\\ volunteering,\\ membership,\\ market\\ days,\\ free\\ food. author Sarah\\ McLean
vti_charset:SR|utf-8
