vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|06 Sep 2026 09:09:05 -0000
vti_extenderversion:SR|12.0.0.0
vti_backlinkinfo:VX|milestones/milestones.php contribute/request_sponsorship.php admin/edit_group_events.php administration/add_sponsor.php admin/html_4_beginners.php sponsors/sponsors.php group_events/group_events.php admin/expression_web_4_beginners.php admin/javascript_4_beginners.php administration/governance.php administration/html_4_beginners.php administration/test.php MobileApp/MobileApp.php index_copy(1).php contribute/join.php governance/governance.php site_history/site_history.php administration/edit_group_events.php administration/web_diagnostics.php admin/web_diagnostics.php contribute/contribute.php admin/edit_sponsor.php administration/expression_web_4_beginners.php administration/javascript_4_beginners.php admin/css_4_beginners.php admin/edit_groups.php admin/friday_feast_menu.php contact/contact.php contribute/volunteering.php people/people.php administration/administration.php administration/css_4_beginners.php administration/edit_groups.php administration/edit_sponsor.php admin/administration.php admin/governance.php Calendar/calendar.php contribute/donation.php contribute/sponsorship_request_sent.php contribute/why_donate.php about/about.php room/room.php administration/group_photo.php admin/add_sponsor.php administration/friday_feast_menu.php
vti_author:SR|LATITUDE-E5430\\gregaryb
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timecreated:TR|10 Aug 2026 16:43:27 -0000
vti_title:SR|Hire a room
vti_nexttolasttimemodified:TR|06 Sep 2026 09:04:34 -0000
vti_cacheddtm:TX|06 Sep 2026 09:09:05 -0000
vti_filesize:IR|40339
vti_cachedtitle:SR|Hire a room
vti_cachedbodystyle:SR|<body onload="DoOnPageLoadComplete()">
vti_cachedlinkinfo:VX|G|../master.dwt H|https://www.millhouse.org.au/ Q|../styles/style4PC.css H|../favicon.jpg S|../common.js H|https://fonts.googleapis.com H|https://fonts.gstatic.com Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 H|../images/MillHouse.jpg S|../images/MillHouse.jpg H|../images/MillHouseNeighborhoodHouse1.jpg S|../images/MillHouseNeighborhoodHouse1.jpg H|../index.php H|../about/about.php H|../calendar/calendar.php H|room.php H|../sponsors/sponsors.php H|../contribute/contribute.php H|../contribute/join.php H|../contribute/volunteering.php H|../contribute/request_sponsorship.php H|../contribute/donation.php H|../contact/contact.php H|../site_history/site_history.php H|../governance/governance.php H|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile H|../governance/rules/rules.php H|../governance/reports/reports.php H|../governance/policies/policies.php H|../governance/plan/plan.php H|../administration/administration.php S|../images/LoudSpeaker.png S|images/kitchen2.jpg S|images/kitchen2.jpg
vti_cachedsvcrellinks:VX|FGUS|master.dwt NHSS|https://www.millhouse.org.au/ FQUS|styles/style4PC.css FHUS|favicon.jpg FSUS|common.js NHSS|https://fonts.googleapis.com NHSS|https://fonts.gstatic.com NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 FHUS|images/MillHouse.jpg FSUS|images/MillHouse.jpg FHUS|images/MillHouseNeighborhoodHouse1.jpg FSUS|images/MillHouseNeighborhoodHouse1.jpg FHUS|index.php FHUS|about/about.php FHUS|calendar/calendar.php FHUS|room/room.php FHUS|sponsors/sponsors.php FHUS|contribute/contribute.php FHUS|contribute/join.php FHUS|contribute/volunteering.php FHUS|contribute/request_sponsorship.php FHUS|contribute/donation.php FHUS|contact/contact.php FHUS|site_history/site_history.php FHUS|governance/governance.php NHSS|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile FHUS|governance/rules/rules.php FHUS|governance/reports/reports.php FHUS|governance/policies/policies.php FHUS|governance/plan/plan.php FHUS|administration/administration.php FSUS|images/LoudSpeaker.png FSUS|room/images/kitchen2.jpg FSUS|room/images/kitchen2.jpg
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8 viewport width=device-width,\\ initial-scale=1.0 description Mill\\ House\\ -\\ Neighborhood\\ House.\\ Providing\\ assistance\\ and\\ social\\ engagement\\ to\\ residents\\ of\\ Maryborough\\ and\\ the\\ central\\ goldfields\\ region. keywords Maryborough,\\ central\\ goldfields,\\ NIL,\\ no\\ interest\\ loans,\\ employment\\ services,\\ clubs,\\ hobbies,\\ Friday\\ feast,\\ Thursday\\ cafe,\\ volunteering,\\ membership,\\ market\\ days,\\ free\\ food. author Sarah\\ McLean
vti_charset:SR|utf-8
