vti_encoding:SR|utf8-nl
vti_author:SR|LATITUDE-E5430\\gregaryb
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timelastmodified:TR|14 Sep 2026 12:08:00 -0000
vti_timecreated:TR|13 Sep 2026 07:47:12 -0000
vti_title:SR|Youth Hub
vti_extenderversion:SR|12.0.0.0
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|14 Sep 2026 11:08:17 -0000
vti_cacheddtm:TX|14 Sep 2026 12:08:00 -0000
vti_filesize:IR|19066
vti_cachedtitle:SR|Youth Hub
vti_cachedbodystyle:SR|<body onload="DoOnPageLoadComplete()">
vti_cachedlinkinfo:VX|G|../../master.dwt H|https://www.millhouse.org.au/ Q|../../styles/style4PC.css H|../../favicon.jpg S|../../common.js H|https://fonts.googleapis.com H|https://fonts.gstatic.com Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 H|../../images/MillHouse.jpg S|../../images/MillHouse.jpg H|../../images/MillHouseNeighborhoodHouse1.jpg S|../../images/MillHouseNeighborhoodHouse1.jpg H|../../images/MillHouseNeighborhoodHouse2.jpg S|../../images/MillHouseNeighborhoodHouse2.jpg S|../../images/LoudSpeaker.png H|../../contribute/donation.php S|../../MobileApp/images/Donate.png H|../../index.php H|../../about/about.php H|../../people/people.php H|../../milestones/milestones.php H|../../site_history/site_history.php H|../what.php H|../../digital/digital.php H|../../youth/youth.php H|../../activities/activities.php H|../../support/support.php H|../../food/food.php H|../../calendar/calendar.php H|../../room/room.php H|../../sponsors/sponsors.php H|../../contribute/contribute.php H|../../contribute/join.php H|../../contribute/volunteering.php H|../../contribute/request_sponsorship.php H|../../contribute/donation.php H|../../contact/contact.php H|../../governance/governance.php H|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile H|../../governance/rules/rules.php H|../../governance/reports/reports.php H|../../governance/policies/policies.php H|../../governance/plan/plan.php H|../../administration/administration.php H|../../index.php H|../../about/about.php H|../../clendar/calendar.php H|../../room/room.php H|../../sponsors/sponsors.php H|../../contact/contact.php S|../../images/AudioOnOff.png S|../../images/ChooseVoice.png S|../../images/Speaker.png S|../../images/StopWatch.png S|../../images/TuningFork.png S|../../images/ReadText.png H|../../images/influencers.jpg S|../../images/influencers.jpg H|../groups/images/dungeons_dragons1.jpg S|../groups/images/dungeons_dragons1.jpg H|../groups/images/dungeons_dragons2.jpg S|../groups/images/dungeons_dragons2.jpg H|../../images/gamers.jpg S|../../images/gamers.jpg H|images/gamers.jpg S|images/gamers.jpg H|../../images/youth_hub.jpg S|../../images/youth_hub.jpg
vti_cachedsvcrellinks:VX|FGUS|master.dwt NHSS|https://www.millhouse.org.au/ FQUS|styles/style4PC.css FHUS|favicon.jpg FSUS|common.js NHSS|https://fonts.googleapis.com NHSS|https://fonts.gstatic.com NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 FHUS|images/MillHouse.jpg FSUS|images/MillHouse.jpg FHUS|images/MillHouseNeighborhoodHouse1.jpg FSUS|images/MillHouseNeighborhoodHouse1.jpg FHUS|images/MillHouseNeighborhoodHouse2.jpg FSUS|images/MillHouseNeighborhoodHouse2.jpg FSUS|images/LoudSpeaker.png FHUS|contribute/donation.php FSUS|MobileApp/images/Donate.png FHUS|index.php FHUS|about/about.php FHUS|people/people.php FHUS|milestones/milestones.php FHUS|site_history/site_history.php FHUS|what/what.php NHUS|digital/digital.php NHUS|youth/youth.php NHUS|activities/activities.php NHUS|support/support.php NHUS|food/food.php FHUS|calendar/calendar.php FHUS|room/room.php FHUS|sponsors/sponsors.php FHUS|contribute/contribute.php FHUS|contribute/join.php FHUS|contribute/volunteering.php FHUS|contribute/request_sponsorship.php FHUS|contribute/donation.php FHUS|contact/contact.php FHUS|governance/governance.php NHSS|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile FHUS|governance/rules/rules.php FHUS|governance/reports/reports.php FHUS|governance/policies/policies.php FHUS|governance/plan/plan.php FHUS|administration/administration.php FHUS|index.php FHUS|about/about.php NHUS|clendar/calendar.php FHUS|room/room.php FHUS|sponsors/sponsors.php FHUS|contact/contact.php FSUS|images/AudioOnOff.png FSUS|images/ChooseVoice.png FSUS|images/Speaker.png FSUS|images/StopWatch.png FSUS|images/TuningFork.png FSUS|images/ReadText.png FHUS|images/influencers.jpg FSUS|images/influencers.jpg FHUS|what/groups/images/dungeons_dragons1.jpg FSUS|what/groups/images/dungeons_dragons1.jpg FHUS|what/groups/images/dungeons_dragons2.jpg FSUS|what/groups/images/dungeons_dragons2.jpg FHUS|images/gamers.jpg FSUS|images/gamers.jpg FHUS|what/youth/images/gamers.jpg FSUS|what/youth/images/gamers.jpg FHUS|images/youth_hub.jpg FSUS|images/youth_hub.jpg
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8 viewport width=device-width,\\ initial-scale=1.0 description Mill\\ House\\ -\\ Neighborhood\\ House.\\ Providing\\ assistance\\ and\\ social\\ engagement\\ to\\ residents\\ of\\ Maryborough\\ and\\ the\\ central\\ goldfields\\ region. keywords Maryborough,\\ central\\ goldfields,\\ NIL,\\ no\\ interest\\ loans,\\ employment\\ services,\\ clubs,\\ hobbies,\\ Friday\\ feast,\\ Thursday\\ cafe,\\ volunteering,\\ membership,\\ market\\ days,\\ free\\ food. author Sarah\\ McLean
vti_charset:SR|utf-8
