vti_encoding:SR|utf8-nl
vti_author:SR|LATITUDE-E5430\\gregaryb
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timelastmodified:TR|27 Jul 2026 05:44:48 -0000
vti_timecreated:TR|26 Jul 2025 05:25:40 -0000
vti_title:SR|Make a Donation
vti_extenderversion:SR|12.0.0.0
vti_nexttolasttimemodified:TR|27 Jul 2026 05:43:49 -0000
vti_structuredtm:TR|30 Jul 2025 09:00:38 -0000
vti_backlinkinfo:VX|admin/approve_sponsorship.php milestones/milestones.php admin/html_4_beginners.php governance/rules/rules.php groups/groups\\ .php sponsors/sponsors.php admin/expression_web_4_beginners.php admin/javascript_4_beginners.php governance/forms/forms.php contribute/join.php about/about.php governance/governance.php room/room.php site_history/site_history.php governance/reports/reports.php governance/policies/policies.php request_sponsorship.php admin/web_diagnostics.php governance/plan/plan.php index.php contribute/contribute.php sponsorship_request_sent.php master.dwt admin/css_4_beginners.php admin/edit_groups.php contact/contact.php contribute/volunteering.php people/people.php admin/friday_feast_menu.php admin/renew_sponsorship.php Calendar/calendar.php admin/administration.php contribute/donation.php contribute/why_donate.php admin/governance.php
vti_cacheddtm:TX|27 Jul 2026 05:44:48 -0000
vti_filesize:IR|20044
vti_cachedtitle:SR|Make a Donation
vti_cachedbodystyle:SR|<body onload="DoOnPageLoadComplete()">
vti_cachedlinkinfo:VX|G|../master.dwt H|https://www.millhouse.org.au/ Q|../styles/style4PC.css H|../favicon.jpg S|../common.js H|https://fonts.googleapis.com H|https://fonts.gstatic.com Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 H|../images/MillHouse.jpg S|../images/MillHouse.jpg H|../images/MillHouseNeighborhoodHouse1.jpg S|../images/MillHouseNeighborhoodHouse1.jpg H|../images/MillHouseNeighborhoodHouse2.jpg S|../images/MillHouseNeighborhoodHouse2.jpg S|../sponsors/images/NHHV.png S|../sponsors/images/VicStateGov.jpg S|../sponsors/images/CentralGoldfields.png S|../sponsors/images/FRRR.png S|../sponsors/images/BendigoBank.jpg S|../sponsors/images/JWR.png S|../sponsors/images/WattleOffice.jpg S|../sponsors/images/FoodBank.png S|../sponsors/images/FoodShare.png S|../sponsors/images/Aldi.png S|../sponsors/images/ParkviewBakery.jpg S|../sponsors/images/MaryboroughFloorCoverings.jpg S|../sponsors/images/SilverService.png S|../sponsors/images/GoldfieldsScreens.png H|../index.php H|../about/about.php H|../Calendar/Calendar.php H|../room/room.php H|../sponsors/sponsors.php H|contribute.php H|join.php H|volunteering.php H|../request_sponsorship.php H|donation.php H|../contact/Contact.php H|../site_history/site_history.php H|../governance/governance.php H|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile H|../governance/rules/rules.php H|../governance/reports/reports.php H|../governance/policies/policies.php H|../governance/plan/plan.php H|../admin/administration.php H|../admin/edit_groups.php H|../admin/approve_sponsorship.php H|../admin/renew_sponsorship.php H|../admin/friday_feast_menu.php H|../admin/governance.php H|../governance/forms/forms.php H|../admin/web_diagnostics.php H|../admin/html_4_beginners.php H|../admin/css_4_beginners.php H|../admin/javascript_4_beginners.php H|../admin/expression_web_4_beginners.php A|\\\\donation_receipt.php
vti_cachedsvcrellinks:VX|FGUS|master.dwt NHSS|https://www.millhouse.org.au/ FQUS|styles/style4PC.css NHUS|favicon.jpg FSUS|common.js NHSS|https://fonts.googleapis.com NHSS|https://fonts.gstatic.com NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 FHUS|images/MillHouse.jpg FSUS|images/MillHouse.jpg FHUS|images/MillHouseNeighborhoodHouse1.jpg FSUS|images/MillHouseNeighborhoodHouse1.jpg FHUS|images/MillHouseNeighborhoodHouse2.jpg FSUS|images/MillHouseNeighborhoodHouse2.jpg FSUS|sponsors/images/NHHV.png FSUS|sponsors/images/VicStateGov.jpg FSUS|sponsors/images/CentralGoldfields.png FSUS|sponsors/images/FRRR.png FSUS|sponsors/images/BendigoBank.jpg FSUS|sponsors/images/JWR.png FSUS|sponsors/images/WattleOffice.jpg FSUS|sponsors/images/FoodBank.png FSUS|sponsors/images/FoodShare.png FSUS|sponsors/images/Aldi.png FSUS|sponsors/images/ParkviewBakery.jpg FSUS|sponsors/images/MaryboroughFloorCoverings.jpg FSUS|sponsors/images/SilverService.png FSUS|sponsors/images/GoldfieldsScreens.png FHUS|index.php FHUS|about/about.php FHUS|Calendar/Calendar.php FHUS|room/room.php FHUS|sponsors/sponsors.php FHUS|contribute/contribute.php FHUS|contribute/join.php FHUS|contribute/volunteering.php FHUS|request_sponsorship.php FHUS|contribute/donation.php FHUS|contact/Contact.php FHUS|site_history/site_history.php FHUS|governance/governance.php NHSS|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile FHUS|governance/rules/rules.php FHUS|governance/reports/reports.php FHUS|governance/policies/policies.php FHUS|governance/plan/plan.php FHUS|admin/administration.php FHUS|admin/edit_groups.php FHUS|admin/approve_sponsorship.php FHUS|admin/renew_sponsorship.php FHUS|admin/friday_feast_menu.php FHUS|admin/governance.php FHUS|governance/forms/forms.php FHUS|admin/web_diagnostics.php FHUS|admin/html_4_beginners.php FHUS|admin/css_4_beginners.php FHUS|admin/javascript_4_beginners.php FHUS|admin/expression_web_4_beginners.php NAUS|file:///C:/Users/gregaryb/Documents/GitHub/Millhouse-Website/contribute/\\\\donation_receipt.php
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8 viewport width=device-width,\\ initial-scale=1.0 description Mill\\ House\\ -\\ Neighborhood\\ House.\\ Providing\\ assistance\\ and\\ social\\ engagement\\ to\\ residents\\ of\\ Maryborough\\ and\\ the\\ central\\ goldfields\\ region. keywords Maryborough,\\ central\\ goldfields,\\ NIL,\\ no\\ interest\\ loans,\\ employment\\ services,\\ clubs,\\ hobbies,\\ Friday\\ feast,\\ Thursday\\ cafe,\\ volunteering,\\ membership,\\ market\\ days,\\ free\\ food. author Sarah\\ McLean
vti_charset:SR|utf-8
