vti_encoding:SR|utf8-nl
vti_author:SR|LATITUDE-E5430\\gregaryb
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timelastmodified:TR|27 Jul 2026 05:44:57 -0000
vti_timecreated:TR|26 Jul 2025 05:25:40 -0000
vti_title:SR|Home
vti_extenderversion:SR|12.0.0.0
vti_nexttolasttimemodified:TR|27 Jul 2026 05:43:59 -0000
vti_structuredtm:TR|18 Mar 2026 03:49:06 -0000
vti_backlinkinfo:VX|milestones/milestones.php admin/approve_sponsorship.php Information/annual_reports/annual_reports.php Information/strategic_plan/strategic_plan.html personnel_history/personnel_history.html admin/expression_web_4_beginners.php admin/javascript_4_beginners.php governance/forms/forms.php ACNC/reports/reports.php ACNC/plan/plan.html Information/association_rules/association_rules.html contribute/join.php site_history/site_history.php governance/governance.php governance/reports/reports.php governance/policies/policies.php request_sponsorship.php Information/cool_space/cool_space.html CoolSpace/information.html admin/web_diagnostics.php index.php governance/plan/plan.php contribute/contribute.php sponsorship_request_sent.php ACNC/ACNC.html ACNC/policies_rules/policies_rules.php contact/contact.php master.dwt admin/css_4_beginners.php contribute/volunteering.php people/people.php admin/edit_groups.php admin/friday_feast_menu.php events/cyber_cafe/cybercafe.php Information/Policies/policies.html admin/renew_sponsorship.php Calendar/calendar.php admin/administration.php contribute/donation.php contribute/why_donate.php admin/governance.php about/about.php Information/information.html room/room.php admin/html_4_beginners.php groups/groups\\ .php governance/rules/rules.php sponsors/sponsors.php
vti_cacheddtm:TX|27 Jul 2026 05:44:57 -0000
vti_filesize:IR|21997
vti_cachedtitle:SR|Home
vti_cachedbodystyle:SR|<body onload="DoOnPageLoadComplete()">
vti_cachedlinkinfo:VX|G|master.dwt H|https://www.millhouse.org.au/ Q|styles/style4PC.css H|./favicon.jpg S|common.js H|https://fonts.googleapis.com H|https://fonts.gstatic.com Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 H|images/MillHouse.jpg S|images/MillHouse.jpg H|images/MillHouseNeighborhoodHouse1.jpg S|images/MillHouseNeighborhoodHouse1.jpg H|images/MillHouseNeighborhoodHouse2.jpg S|images/MillHouseNeighborhoodHouse2.jpg S|sponsors/images/NHHV.png S|sponsors/images/VicStateGov.jpg S|sponsors/images/CentralGoldfields.png S|sponsors/images/FRRR.png S|sponsors/images/BendigoBank.jpg S|sponsors/images/JWR.png S|sponsors/images/WattleOffice.jpg S|sponsors/images/FoodBank.png S|sponsors/images/FoodShare.png S|sponsors/images/Aldi.png S|sponsors/images/ParkviewBakery.jpg S|sponsors/images/MaryboroughFloorCoverings.jpg S|sponsors/images/SilverService.png S|sponsors/images/GoldfieldsScreens.png H|index.php H|about/about.php H|Calendar/Calendar.php H|room/room.php H|sponsors/sponsors.php H|contribute/contribute.php H|contribute/join.php H|contribute/volunteering.php H|request_sponsorship.php H|contribute/donation.php H|contact/Contact.php H|site_history/site_history.php H|governance/governance.php H|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile H|governance/rules/rules.php H|governance/reports/reports.php H|governance/policies/policies.php H|governance/plan/plan.php H|admin/administration.php H|admin/edit_groups.php H|admin/approve_sponsorship.php H|admin/renew_sponsorship.php H|admin/friday_feast_menu.php H|admin/governance.php H|governance/forms/forms.php H|admin/web_diagnostics.php H|admin/html_4_beginners.php H|admin/css_4_beginners.php H|admin/javascript_4_beginners.php H|admin/expression_web_4_beginners.php S|images/MillHouseTeam.jpg K|index.php H|javascript:void(0) H|javascript:void(0) H|javascript:void(0) H|javascript:void(0) H|javascript:void(0) H|javascript:void(0) S|images/IndigenousFlag.jpg S|images/DjaDjaWarrung.png S|images/ToresStraitIslandFlag.jpg
vti_cachedsvcrellinks:VX|FGUS|master.dwt NHSS|https://www.millhouse.org.au/ FQUS|styles/style4PC.css NHUS|favicon.jpg FSUS|common.js NHSS|https://fonts.googleapis.com NHSS|https://fonts.gstatic.com NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 FHUS|images/MillHouse.jpg FSUS|images/MillHouse.jpg FHUS|images/MillHouseNeighborhoodHouse1.jpg FSUS|images/MillHouseNeighborhoodHouse1.jpg FHUS|images/MillHouseNeighborhoodHouse2.jpg FSUS|images/MillHouseNeighborhoodHouse2.jpg FSUS|sponsors/images/NHHV.png FSUS|sponsors/images/VicStateGov.jpg FSUS|sponsors/images/CentralGoldfields.png FSUS|sponsors/images/FRRR.png FSUS|sponsors/images/BendigoBank.jpg FSUS|sponsors/images/JWR.png FSUS|sponsors/images/WattleOffice.jpg FSUS|sponsors/images/FoodBank.png FSUS|sponsors/images/FoodShare.png FSUS|sponsors/images/Aldi.png FSUS|sponsors/images/ParkviewBakery.jpg FSUS|sponsors/images/MaryboroughFloorCoverings.jpg FSUS|sponsors/images/SilverService.png FSUS|sponsors/images/GoldfieldsScreens.png FHUS|index.php FHUS|about/about.php FHUS|Calendar/Calendar.php FHUS|room/room.php FHUS|sponsors/sponsors.php FHUS|contribute/contribute.php FHUS|contribute/join.php FHUS|contribute/volunteering.php FHUS|request_sponsorship.php FHUS|contribute/donation.php FHUS|contact/Contact.php FHUS|site_history/site_history.php FHUS|governance/governance.php NHSS|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile FHUS|governance/rules/rules.php FHUS|governance/reports/reports.php FHUS|governance/policies/policies.php FHUS|governance/plan/plan.php FHUS|admin/administration.php FHUS|admin/edit_groups.php FHUS|admin/approve_sponsorship.php FHUS|admin/renew_sponsorship.php FHUS|admin/friday_feast_menu.php FHUS|admin/governance.php FHUS|governance/forms/forms.php FHUS|admin/web_diagnostics.php FHUS|admin/html_4_beginners.php FHUS|admin/css_4_beginners.php FHUS|admin/javascript_4_beginners.php FHUS|admin/expression_web_4_beginners.php FSUS|images/MillHouseTeam.jpg FKUS|index.php SHUS|javascript:void(0) SHUS|javascript:void(0) SHUS|javascript:void(0) SHUS|javascript:void(0) SHUS|javascript:void(0) SHUS|javascript:void(0) FSUS|images/IndigenousFlag.jpg FSUS|images/DjaDjaWarrung.png FSUS|images/ToresStraitIslandFlag.jpg
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8 viewport width=device-width,\\ initial-scale=1.0 description Mill\\ House\\ -\\ Neighborhood\\ House.\\ Providing\\ assistance\\ and\\ social\\ engagement\\ to\\ residents\\ of\\ Maryborough\\ and\\ the\\ central\\ goldfields\\ region. keywords Maryborough,\\ central\\ goldfields,\\ NIL,\\ no\\ interest\\ loans,\\ employment\\ services,\\ clubs,\\ hobbies,\\ Friday\\ feast,\\ Thursday\\ cafe,\\ volunteering,\\ membership,\\ market\\ days,\\ free\\ food. author Sarah\\ McLean
vti_charset:SR|utf-8
