vti_encoding:SR|utf8-nl
vti_author:SR|LATITUDE-E5430\\gregaryb
vti_modifiedby:SR|LATITUDE-E5430\\gregaryb
vti_timelastmodified:TR|25 Sep 2026 10:34:23 -0000
vti_timecreated:TR|26 Jul 2025 05:25:40 -0000
vti_extenderversion:SR|12.0.0.0
vti_nexttolasttimemodified:TW|25 Sep 2026 07:04:13 -0000
vti_structuredtm:TR|18 Mar 2026 03:49:06 -0000
vti_backlinkinfo:VX|admin/edit_group_events.php contribute/request_sponsorship.php Information/annual_reports/annual_reports.php administration/add_sponsor.php administration/governance.php administration/html_4_beginners.php what/support/support.php administration/web_diagnostics.php governance/reports/reports.php governance/policies/policies.php about/site_history/site_history.php CoolSpace/information.html admin/web_diagnostics.php index.php what/youth/youth.php administration/javascript_4_beginners.php what/what.php governance/plan/plan.php ACNC/policies_rules/policies_rules.php contact/contact.php contribute/volunteering.php administration/administration.php administration/edit_groups.php administration/edit_sponsor.php what/groups/groups.php about/milestones/milestones.php Information/Policies/policies.html contribute/sponsorship_request_sent.php Calendar/calendar.php contribute/why_donate.php admin/governance.php about/about.php Information/information.html room/room.php administration/group_photo.php what/food/food.php what/digital/digital.php admin/add_sponsor.php administration/friday_feast_menu.php what/meetings/meetings.php about/people/people.php admin/html_4_beginners.php sponsors/sponsors.php governance/rules/rules.php group_events/group_events.php Information/strategic_plan/strategic_plan.html personnel_history/personnel_history.html admin/expression_web_4_beginners.php admin/javascript_4_beginners.php governance/forms/forms.php administration/test.php MobileApp/MobileApp.php ACNC/reports/reports.php ACNC/plan/plan.html Information/association_rules/association_rules.html contribute/join.php governance/governance.php administration/edit_group_events.php Information/cool_space/cool_space.html contribute/contribute.php admin/edit_sponsor.php administration/expression_web_4_beginners.php ACNC/ACNC.html master.dwt admin/css_4_beginners.php administration/css_4_beginners.php admin/edit_groups.php admin/friday_feast_menu.php events/cyber_cafe/cybercafe.php admin/administration.php contribute/donation.php
vti_title:SR|HOME
vti_cacheddtm:TX|25 Sep 2026 10:34:23 -0000
vti_filesize:IR|39010
vti_cachedtitle:SR|HOME
vti_cachedbodystyle:SR|<body onload="DoOnPageLoadComplete()">
vti_cachedlinkinfo:VX|G|master.dwt H|https://www.millhouse.org.au/ Q|styles/style4PC.css H|./favicon.jpg S|common.js H|https://fonts.googleapis.com H|https://fonts.gstatic.com Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 Q|https://fonts.googleapis.com/css2 H|images/MillHouse.jpg S|images/MillHouse.jpg H|images/MillHouseNeighborhoodHouse1.jpg S|images/MillHouseNeighborhoodHouse1.jpg H|images/MillHouseNeighborhoodHouse2.jpg S|images/MillHouseNeighborhoodHouse2.jpg S|images/LoudSpeaker.png H|contribute/donation.php S|MobileApp/images/Donate.png H|index.php H|about/about.php H|about/people/people.php H|about/milestones/milestones.php H|about/site_history/site_history.php H|what/what.php H|what/meetings/meetings.php H|what/digital/digital.php H|what/food/food.php H|what/groups/groups.php H|what/support/support.php H|what/youth/youth.php H|calendar/calendar.php H|room/room.php H|sponsors/sponsors.php H|contribute/contribute.php H|contribute/join.php H|contribute/volunteering.php H|contribute/request_sponsorship.php H|contribute/donation.php H|contact/contact.php H|governance/governance.php H|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile H|governance/rules/rules.php H|governance/reports/reports.php H|governance/policies/policies.php H|governance/plan/plan.php H|administration/administration.php H|index.php H|about/about.php H|calendar/calendar.php H|room/room.php H|contact/contact.php S|images/AudioOnOff.png S|images/ChooseVoice.png S|images/Speaker.png S|images/StopWatch.png S|images/TuningFork.png S|images/ReadText.png H|images/Spooktacular.jpg S|images/Spooktacular.jpg H|images/influencers.jpg S|images/influencers.jpg S|James\\ Hollands\\ on\\ Reels.mp4 H|newsletter.pdf H|images/Mural1.jpg S|images/Mural1.jpg H|images/Mural2.jpg S|images/Mural2.jpg H|images/Mural3.jpg S|images/Mural3.jpg H|images/Mural4.jpg S|images/Mural4.jpg K|about/about.php K|about/about.php K|about/about.php K|about/about.php H|room/room.php H|contribute/volunteering.php S|images/IndigenousFlag.jpg S|images/DjaDjaWarrung.png S|images/ToresStraitIslandFlag.jpg
vti_cachedsvcrellinks:VX|FGUS|master.dwt NHSS|https://www.millhouse.org.au/ FQUS|styles/style4PC.css FHUS|favicon.jpg FSUS|common.js NHSS|https://fonts.googleapis.com NHSS|https://fonts.gstatic.com NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 NQSS|https://fonts.googleapis.com/css2 FHUS|images/MillHouse.jpg FSUS|images/MillHouse.jpg FHUS|images/MillHouseNeighborhoodHouse1.jpg FSUS|images/MillHouseNeighborhoodHouse1.jpg FHUS|images/MillHouseNeighborhoodHouse2.jpg FSUS|images/MillHouseNeighborhoodHouse2.jpg FSUS|images/LoudSpeaker.png FHUS|contribute/donation.php FSUS|MobileApp/images/Donate.png FHUS|index.php FHUS|about/about.php FHUS|about/people/people.php FHUS|about/milestones/milestones.php FHUS|about/site_history/site_history.php FHUS|what/what.php FHUS|what/meetings/meetings.php FHUS|what/digital/digital.php FHUS|what/food/food.php FHUS|what/groups/groups.php FHUS|what/support/support.php FHUS|what/youth/youth.php FHUS|calendar/calendar.php FHUS|room/room.php FHUS|sponsors/sponsors.php FHUS|contribute/contribute.php FHUS|contribute/join.php FHUS|contribute/volunteering.php FHUS|contribute/request_sponsorship.php FHUS|contribute/donation.php FHUS|contact/contact.php FHUS|governance/governance.php NHSS|https://www.acnc.gov.au/charity/charities/a49d2dd7-2daf-e811-a960-000d3ad24282/profile FHUS|governance/rules/rules.php FHUS|governance/reports/reports.php FHUS|governance/policies/policies.php FHUS|governance/plan/plan.php FHUS|administration/administration.php FHUS|index.php FHUS|about/about.php FHUS|calendar/calendar.php FHUS|room/room.php FHUS|contact/contact.php FSUS|images/AudioOnOff.png FSUS|images/ChooseVoice.png FSUS|images/Speaker.png FSUS|images/StopWatch.png FSUS|images/TuningFork.png FSUS|images/ReadText.png FHUS|images/Spooktacular.jpg FSUS|images/Spooktacular.jpg FHUS|images/influencers.jpg FSUS|images/influencers.jpg FSUS|James\\ Hollands\\ on\\ Reels.mp4 FHUS|newsletter.pdf FHUS|images/Mural1.jpg FSUS|images/Mural1.jpg FHUS|images/Mural2.jpg FSUS|images/Mural2.jpg FHUS|images/Mural3.jpg FSUS|images/Mural3.jpg FHUS|images/Mural4.jpg FSUS|images/Mural4.jpg FHUS|about/about.php FHUS|about/about.php FHUS|about/about.php FHUS|about/about.php FHUS|room/room.php FHUS|contribute/volunteering.php FSUS|images/IndigenousFlag.jpg FSUS|images/DjaDjaWarrung.png FSUS|images/ToresStraitIslandFlag.jpg
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8 viewport width=device-width,\\ initial-scale=1.0 description Mill\\ House\\ -\\ Neighborhood\\ House.\\ Providing\\ assistance\\ and\\ social\\ engagement\\ to\\ residents\\ of\\ Maryborough\\ and\\ the\\ central\\ goldfields\\ region. keywords Maryborough,\\ central\\ goldfields,\\ NIL,\\ no\\ interest\\ loans,\\ employment\\ services,\\ clubs,\\ hobbies,\\ Friday\\ feast,\\ Thursday\\ cafe,\\ volunteering,\\ membership,\\ market\\ days,\\ free\\ food. author Sarah\\ McLean
vti_charset:SR|utf-8
